---
# docker
docker_apt_key_id: "58118E89F3A912897C070ADBF76221572C52609D"
docker_apt_key_url: "hkp://p80.pool.sks-keyservers.net:80"
docker_apt_repo_url: "https://apt.dockerproject.org/repo ubuntu-xenial main"

# apt packages
apt_packages:
  - apt-transport-https
  - ca-certificates
  - htop
  - docker-engine
  - python-dev
  - python-pip

# drone
system_data_dir: "/data"
drone_local_dir_path: "{{ system_data_dir }}/drone"
drone_github_config_url: "{{ lookup('env', 'DRONE_GITHUB_URL') }}"
drone_github_client_id: "{{ lookup('env', 'DRONE_GITHUB_CLIENT_ID') }}"
drone_github_client_secret: "{{ lookup('env', 'DRONE_GITHUB_CLIENT_SECRET') }}"
drone_open: "{{ lookup('env', 'DRONE_OPEN') }}"
drone_admin: "{{ lookup('env', 'DRONE_ADMIN') }}"
drone_agent_secret: "{{ lookup('env', 'DRONE_AGENT_SECRET') }}"

